name: dotnet
on: push
jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    - run: |
        dotnet pack \
        -c Release \
        -o dist \
        -p:PackageID=VerismoHR.${{github.event.repository.name}} \
        -p:PackageVersion=1.0.${{github.run_number}} \
        -p:RepositoryUrl=${{github.repositoryUrl}}
    - run: |
        dotnet nuget push \
        dist/**/*.nupkg \
        -k ${{github.token}} \
        -s https://nuget.pkg.github.com/verismohr/index.json \
        --skip-duplicate